### ISSUE TITLE
Error when DjangoProjectActivate

### ISSUE THREAD

**Issue by Zorig** [cwood/vim-django#10]
When trying to activate Project it gives this error
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/app_direc
tories.py", line 33, in <module>
    app_template_dirs = calculate_app_template_dirs()
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/app_direc
tories.py", line 21, in calculate_app_template_dirs
    for app_config in apps.get_app_configs():
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 13
7, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 12
4, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by cwood** [comment]
Hey @Zorig thanks for reporting this. Ill take a look soon. I assume your projects manage.py is working fine. Probably a issue with django 1.7 and the way vim-django activates projects.

**Comment by Zorig** [comment]
yeah, yeah, i was thinking that one too, because when i was working in
django 1.6, 1.5, 1.4 it was fine. And when it becomes 1.7 got this issue

On Sun, Mar 8, 2015 at 3:55 PM, Colin Wood <notifications@github.com> wrote:

> Hey @Zorig <https://github.com/Zorig> thanks for reporting this. Ill take
> a look soon. I assume your projects manage.py is working fine. Probably a
> issue with django 1.7 and the way vim-django activates projects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwood/vim-django/issues/10#issuecomment-77737834>.
>



-- 
*~Regards:*

   - *http://plus.google.com/+ZorigGanbold*
   <http://plus.google.com/+ZorigGanbold>
   - *http://twitter.com/rizogg <http://twitter.com/rizogg> *
   - *http://facebook.com/zorig.ganbold* <http://facebook.com/zorig.ganbold>

**Comment by Zorig** [comment]
@cwood did you look at it?

**Comment by cwood** [comment]
Sorry not yet real life stuff getting in the way. WIll do it soon.

**Comment by cwood** [comment]
Hey @Zorig Im gunna look at this tonight. Sorry for the delay

**Comment by Zorig** [comment]
good to hear that, plus where should django's *virtualenv* placed? I mean in same directory with same name? 
i used to use **virtualwrapper** and all my **venv** is placed under *.virtuanenv/* folder so, i presumed that it must be in same folder with django project, am i right?

**Comment by cwood** [comment]
If you use the virtualenvwrapper it will work. I use vim-virtualenv to activate it. So if it can activate it so can vim-django.

**Comment by Zorig** [comment]
Is it done? @cwood

**Comment by cwood** [comment]
hey @Zorig it should be fixed now. Just needed to add the django.setup(). Please full down and verify.

**Comment by Zorig** [comment]
Yes, it is, Thank you so much
