### ISSUE TITLE
Error when activating

### ISSUE THREAD

**Issue by narley** [cwood/vim-django#11]
Hi there.

When trying to activate project I get the error bellow. I'm activating virtualenv via terminal and am using django 1.7.

Error detected while processing function django#project#activate..ActivateProj
ect:
line   14:
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ImportError: No module named django
Error detected while processing function django#project#activate:
line   78:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named django.utils.importlib

Any idea what is wrong?

Cheers

**Comment by cwood** [comment]
Probably this line here 

https://github.com/cwood/vim-django/blob/master/autoload/django/project.vim#L82

I assume django1.7 is using importlib now since django1.7 is python2.7 only now. If you want you can make a PR if not ill try to get to this soon.

**Comment by narley** [comment]
Thank you for that!

**Comment by Zorig** [comment]
Did you fixed this @cwood ?

**Comment by cwood** [comment]
I havnt done any commits. But he closed it. This is a open source project and I will except PRs :) If not ill get to it eventully.
